swagger: "2.0"

info:
  title: "Flask Optimo API"
  description: "
  {% for item in data %}
  * {{ item }}
  {% endfor %}
  "
  version: "1.0"

basePath: /api/v1.0/

paths:
  /fibonacci:
    post:
      operationId: fci.api.fibonacci.post
      parameters:
        - name: body
          in: 'body'
          required: true
          schema:
            type: object
            properties:
              index:
                type: integer
      responses:
        '200':
          description: 'Get fibonacci sequence'
          schema:
            $ref: '#/definitions/FibonacciResponse'

  /hello/{name}:
    get:
      operationId: fci.api.hello.get
      parameters:
        - name: 'name'
          in: 'path'
          required: true
          type: string
      responses:
        '200':
          description: 'Say hello'
          schema:
            type: object
            properties:
              message: { type: string }

definitions:
  FibonacciResponse:
    type: object
    properties:
      index: { type: integer }
      value: { type: array, items: { type: integer }}
